// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrPZnACPpdw3knsORjLiqWlINX81sLOs',
    appId: '1:235442600192:web:874f85296a88f6c5d49be5',
    messagingSenderId: '235442600192',
    projectId: 'cliqs-703c4',
    authDomain: 'cliqs-703c4.firebaseapp.com',
    storageBucket: 'cliqs-703c4.firebasestorage.app',
    measurementId: 'G-YLVZGSM3B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWJx9C0Jy2Uw1RCJolbt_NLlPJ-uNIoU',
    appId: '1:235442600192:android:636a4582cba2480ed49be5',
    messagingSenderId: '235442600192',
    projectId: 'cliqs-703c4',
    storageBucket: 'cliqs-703c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSRh3q6sS9w_SCDwdV-0X6u4Q3Fy2-fk',
    appId: '1:235442600192:ios:7f1fa39df63d3cd3d49be5',
    messagingSenderId: '235442600192',
    projectId: 'cliqs-703c4',
    storageBucket: 'cliqs-703c4.firebasestorage.app',
    iosBundleId: 'com.example.cliqs',
  );
}
